name: Composite Action "A"

runs:
  using: composite
  steps:
    - name: pwd
      shell: bash
      run: pwd

    - name: echo
      shell: bash
      run: echo "github-actions-experiments/.../actions/a.yml"
