name: Re-Usable workflow "A"

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: | 
          pwd
          echo "github-actions-experiments/.../reusable_a.yml"
   
      - name: job details
        run: |
          echo "job.workflow_sha: ${{ job.workflow_sha }}"
          echo "job.workflow_repository: ${{ job.workflow_repository }}"
